### ISSUE TITLE
Unable to decrypt applelogo im4p

### ISSUE THREAD

**Issue by CrazyDave652** [matteyeux/autodecrypt#10]
As the issue title would suggest, I'm trying to decrypt an im4p but I get this traceback:
```
bash-3.2$ autodecrypt -f applelogo  -d iPhone12,1 -i 14.7 -b 18G69
[i] downloading applelogo@1792~iphone.im4p
Traceback (most recent call last):
  File "/opt/homebrew/bin/autodecrypt", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.8/site-packages/autodecrypt/main.py", line 90, in main
    magic, image_type = decrypt_img.get_image_type(img_file)
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by matteyeux** [comment]
Hello, 

thank you for reporting this bug. I just pushed version 2.2.4, which fixes the issue. You can update it using pip. 

As logos are not encrypted since iOS 10, you can specify `-k 0` so autodecrypt will not try to grab keys which do not exist : 

```
λ ~/ autodecrypt -f applelogo  -d iPhone12,1 -i 14.7 -b 18G69 -k 0
[i] downloading applelogo@1792~iphone.im4p
[i] decrypting applelogo@1792~iphone.im4p to applelogo@1792~iphone.bin...
[x] done
```
