### ISSUE TITLE
SSL Certificate Error

### ISSUE THREAD

**Issue by Starwarsfan2099** [matteyeux/autodecrypt#2]
When I attempt to run the command `./autodecrypt.py -f iBSS.d11.RELEASE.im4p -d iPhone9,2 -i 11.3.1`, or any other command, the tools fails and produces the following error:

```Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1414, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "autodecrypt.py", line 98, in <module>
    build = scrapkeys.version_or_build(device, ios_version, build)
  File "./scrapkeys.py", line 47, in version_or_build
    json_file = urlopen("https://api.ipsw.me/v4/device/" + device)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>```

**Comment by matteyeux** [comment]
I couldn't reproduce the issue : 
```
(env) ➜  autodecrypt git:(master) sw_vers
ProductName:    Mac OS X
ProductVersion: 10.13.6
BuildVersion:   17G65
(env) ➜  autodecrypt git:(master) ./autodecrypt.py -f iBSS.d11.RELEASE.im4p -d iPhone9,2 -i 11.3.1
[i] downloading iBSS.d11.RELEASE.im4p
[i] image : ibss
[i] grabbing keys from https://www.theiphonewiki.com/wiki/Emet_15E302_(iPhone9,2)
[x] iv  : bb72ea450dc63002e397972c0ceb85ce
[x] key : 0d9b2f866e9e05fe9c767d505d001b98783fe3667baf219da24ae3ce453f5b38
[i] decrypting iBSS.d11.RELEASE.im4p to iBSS.d11.RELEASE.im4p.dec...
[x] done
```

By googling the error it seems to be a Python issue with MacOS : https://github.com/hardikvasa/google-images-download/issues/140#issuecomment-435257490

**Comment by Starwarsfan2099** [comment]
It was an error with my local Python installation. Running `open /Applications/Python\ 3.7/Install\ Certificates.command` fixed the error.
