### ISSUE TITLE
KeyError: 'content-range'

### ISSUE THREAD

**Issue by justtryingthingsout** [matteyeux/autodecrypt#8]
```
$ autodecrypt -f iBoot.d321.RELEASE.im4p -d iPhone11,2 -b 17A5492t -i 13.0 --beta
Traceback (most recent call last):
  File "/usr/local/bin/autodecrypt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/autodecrypt/main.py", line 77, in main
    img_file = utils.download_beta_file(parser, json_data)
  File "/usr/local/lib/python3.9/site-packages/autodecrypt/utils.py", line 104, in download_beta_file
    img_file = fw_utils.grab_file(fw_url, parser.img_file)
  File "/usr/local/lib/python3.9/site-packages/autodecrypt/fw_utils.py", line 13, in grab_file
    with RemoteZip(url) as zipfile:
  File "/usr/local/lib/python3.9/site-packages/remotezip.py", line 130, in __init__
    super(RemoteZip, self).__init__(rio)
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zipfile.py", line 1257, in __init__
    self._RealGetContents()
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zipfile.py", line 1320, in _RealGetContents
    endrec = _EndRecData(fp)
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zipfile.py", line 263, in _EndRecData
    fpin.seek(0, 2)
  File "/usr/local/lib/python3.9/site-packages/remotezip.py", line 104, in seek
    self.buffer = self.fetch_fun((-size, None), stream=False)
  File "/usr/local/lib/python3.9/site-packages/remotezip.py", line 170, in fetch_fun
    return self.make_buffer(res, headers['Content-Range'], stream=stream)
  File "/usr/local/lib/python3.9/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-range'
```
this happens even when i say `-f iBoot`, and
I can't just use the build id, since that errors out saying 
```
[i] please specify iOS version
[e] could not grab file
```

**Comment by matteyeux** [comment]
The [URL](https://developer.apple.com/services-account/download?path=/WWDC_2019/iOS_and_tvOS_IPSWs_for_Jun_3_2019_Seed/iPhone112iPhone116_13.0_17A5492t_Restore.ipsw) is not accessible without a dev account.
